site_name: My Blog
nav:
- Home: index.md
- Sample Post: sample.md
- Blogs:
  - Nodejs: docs/Nodejs.md
  - AZURE BLOB STORAGE: docs/AZURE_BLOB_STORAGE.md
  - ASP: docs/ASP.md
  - Microsoft Purview: docs/Microsoft_Purview.md
  - React JS: docs/React_JS.md
  - Azure Data Lake Storage: docs/Azure_Data_Lake_Storage.md
  - CoPilot Studio: docs/COPILOT_STUDIO.md
  - ASP.NET: docs/ASPNET.md
  - Microsoft Graph API: docs/MICROSOFT_GRAPH_API.md
theme:
  name: material
